version: '3'

services:
  mongodb:
    image: mongo:7
    restart: always
    container_name: api_integration
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: api_integration
    volumes:
      - ./data/mongodb:/data/db
